// Generated by CoffeeScript 1.3.3
(function() {
  var exports;

  exports = module.exports = require("./soyer");

  exports.version = '0.1.0';

  exports.helper = require("./helper");

}).call(this);
