// Generated by CoffeeScript 1.6.3
(function() {
  var exports;

  exports = module.exports = require("./soyer");

  exports.version = '0.3.3';

  exports.helper = require("./helper");

}).call(this);
